apiVersion: v1
description: 'stash-elasticsearch - Elasticsearch database backup and restore plugin for Stash by AppsCode'
name: stash-elasticsearch
version: "6.5.3"
appVersion: "6.5.3"
home: https://github.com/stashed/elasticsearch
icon: https://cdn.appscode.com/images/icon/stash.png
sources:
  - https://github.com/stashed/elasticsearch
maintainers:
  - name: appscode
    email: support@appscode.com
